### ISSUE TITLE
vim not support python2.7?

### ISSUE THREAD

**Issue by wiwengweng** [fisadev/fisa-vim-config#101]
Hi, I just install fisa-vim-config, but finally find that I don't have python2.7 support in vim. How can I solve this? Python is installed in my machine

wyl@ubuntu:~$ vim --version | grep python
+cryptv          +linebreak       -python          +vreplace
+cscope          +lispindent      +python3         +wildignore

**Comment by fisadev** [comment]
Hi! I missed this, sorry for the delay. Depending on your ubuntu version, the simplest solution might be installing the vim-nox package:

    sudo apt-get install vim-nox

Hope it helps!

**Comment by wiwengweng** [comment]
ops~thank you. :dancer:
