### ISSUE TITLE
Plugins are making Vim slow

### ISSUE THREAD

**Issue by Amrithasuresh** [fisadev/fisa-vim-config#102]
How do you improve the speed? My vimrc profile is here [vimrc.txt](https://github.com/fisadev/fisa-vim-config/files/860923/vimrc.txt).

I am reading the answers by googling.  

Do you have any tips?  Thank you.

**Comment by chikatambun** [comment]
$ vim -u NONE ....

**Comment by fisadev** [comment]
Closing this, as the new version is way faster (replaced some of the slower plugins with better ones).

**Comment by wAuner** [comment]
can we reopen this? I've install the fisa 1:1 and it is just terrible slow, it's become unuseable. What plugins can I kick out to improve the speed?
