### ISSUE TITLE
vim-scripts' expansion is deprecated

### ISSUE THREAD

**Issue by tinolin** [fisadev/fisa-vim-config#104]
Luego de isntalar, cuando ejecuto vim, arroja esto:

```
[vim-plug] Invalid argument: IndexedSearch (implicit `vim-scripts' expansion is deprecated)
[vim-plug] Invalid argument: matchit.zip (implicit `vim-scripts' expansion is deprecated)
[vim-plug] Invalid argument: Wombat (implicit `vim-scripts' expansion is deprecated)
[vim-plug] Invalid argument: YankRing.vim (implicit `vim-scripts' expansion is deprecated)
```

Obviamente comentando estas lineas en el vimrc todo OK.
en VIM - Vi IMproved 7.4

**Comment by TimePPT** [comment]
Same issue on Ubuntu 17.04, vim 8.0.95

**Comment by fisadev** [comment]
Oh! I need to update the plugin declarations to avoid the implicit convertion to vim-scripts repos. It's an easy fix, will do it tomorrow (right now I'm doing some urgent work).

**Comment by fisadev** [comment]
Done! Relesed as version 8.3.1.

**Comment by TimePPT** [comment]
Great, thanks
