### ISSUE TITLE
When I type to a new line the background color will change to white 

### ISSUE THREAD

**Issue by andy8672** [fisadev/fisa-vim-config#105]
<img width="1680" alt="screen shot 2017-06-06 at 11 34 31 pm" src="https://user-images.githubusercontent.com/29233181/26837804-f453607c-4b10-11e7-8c9b-6c903ee6eecd.png">

**Comment by andy8672** [comment]
<img width="1680" alt="screen shot 2017-06-06 at 11 34 31 pm" src="https://user-images.githubusercontent.com/29233181/26837779-e2f5bb7c-4b10-11e7-88cc-a5df5539c85b.png">

**Comment by andy8672** [comment]
this is my .vimrc file 
[a.txt](https://github.com/fisadev/fisa-vim-config/files/1055626/a.txt)

**Comment by fisadev** [comment]
The colorscheme isn't compatible with custom settings of background, that you added before the scheme is selected. You could remove those customizations, or trying a different colorscheme instead of "fisa".
