### ISSUE TITLE
Run the current python file and display the output on a split with \r.

### ISSUE THREAD

**Issue by zzploveyou** [fisadev/fisa-vim-config#106]
It cannot work.
for a test.py with content: ```print "hello"```
if I input \r, content will change to ``` "hello"```

**Comment by nithinmohan** [comment]
Same for me

**Comment by fisadev** [comment]
Ouch, this was broken at some point in one of the plugin changes, and the docs never got updated. This proyect is no longer maintained, though, it was replaced by github.com/fisadev/fisa-nvim-config
