### ISSUE TITLE
The vim background turns dark with this script!!

### ISSUE THREAD

**Issue by ArashMehraban** [fisadev/fisa-vim-config#110]
I used the script provided here to update the .vimrc, but I get a dark background in vim after this modification. I checked the script for :set background to see if it messes with the background color but it does not contain those words. As I type, the background color change color one character at a time. Please see picture.  file:///home/arash/Pictures/vim-open.png
/home/arash/Pictures/vim-after-typing.png

**Comment by ArashMehraban** [comment]
Not sure why the pics are not uploading!! but the description should be clear

**Comment by fisadev** [comment]
That's the background defined by the colorscheme that I used in this config. You can change it to another colorscheme if you don't like that one, look at the line that says `colorscheme fisa` and change it to your preferred one :)
