### ISSUE TITLE
Which plugin runs python?

### ISSUE THREAD

**Issue by ngt-magee** [fisadev/fisa-vim-config#115]
Which plugin is responsible for this feature: 

`Run the current python file and display the output on a split with \r` (from the features doc)

I've searched and can't figure out

**Comment by fisadev** [comment]
Hi!
That feature was removed when rope-vim has removed, and the docs were outdated. Sorry for that. I've just released a newer version with updated docs among other things.

If you still want that feature, there are some alternatives here: https://stackoverflow.com/questions/18948491/running-python-code-in-vim
