### ISSUE TITLE
issue in vim-hug-neovim-rpc

### ISSUE THREAD

**Issue by erasmussen1** [fisadev/fisa-vim-config#118]
I'm not sure if this issue is already reported, but here it is.

I'm on a fresh Ubuntu 18.04 install with vim version 8.0.1453 and I'm getting following issue when I start vim

[vim-hug-neovim-rpc] Vim(pythonx):Traceback (most recent call last):
Error detected while processing function deoplete#enable[9]..deoplete#initialize[1]..deoplete#init#_initialize[10]..<SNR>109_init_internal_variables[28]..neovim_rpc#serveraddr:
line   18:
E605: Exception not caught: [vim-hug-neovim-rpc] requires one of `:pythonx import [pynvim|neovim]` command to work
Press ENTER or type command to continue

**Comment by junzhilu** [comment]
use pip3 (pip for python3) solves this issue in my case.

**Comment by fisadev** [comment]
Yes, as @junzhilu points out, that's the most probable cause.
