### ISSUE TITLE
Can I use it with Windows? 

### ISSUE THREAD

**Issue by in2Rafi** [fisadev/fisa-vim-config#120]
I am heavy Windows user. My question is would this work in Windows too?

**Comment by Perkosrak** [comment]
Добрый день. К сожалению на windows пока не работает. Чтобы заработало для этой операционной системы, необходимо перенастроить все пути, часть функций работают не так, как задумывалось. Из исходного файла конфигурации, можно убрать всю "автоматику", и запустить все в ручную. Да, зависимости необходимо будет удовлетворить...

**Comment by fisadev** [comment]
Sorry. As @Perkosrak said, some thing won't work under Windows. You could still try and debug which ones and try to tune the config to fix any problems, but it will probably be some work.
