### ISSUE TITLE
Mal certificado para la pagina https://vim.fisadev.com/

### ISSUE THREAD

**Issue by crisofilaxx** [fisadev/fisa-vim-config#122]
Hola Fisa, 

Te comento que el certificado de tu página tiene un common name no válido para tu dominio.

~$ openssl s_client -connect vim.fisadev.com:443
CONNECTED(00000005)
depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert High Assurance EV Root CA
verify return:1
depth=1 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert SHA2 High Assurance Server CA
verify return:1
depth=0 C = US, ST = California, L = San Francisco, O = "GitHub, Inc.", CN = www.github.com
verify return:1
---
Certificate chain
 0 s:C = US, ST = California, L = San Francisco, O = "GitHub, Inc.", CN = www.github.com
   i:C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert SHA2 High Assurance Server CA
 1 s:C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert SHA2 High Assurance Server CA
   i:C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert High Assurance EV Root CA
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIHMTCCBhmgAwIBAgIQDf56dauo4GsS0tOc8/ik/DANBgkqhkiG9w0BAQsFADBw
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMS8wLQYDVQQDEyZEaWdpQ2VydCBTSEEyIEhpZ2ggQXNz
dXJhbmNlIFNlcnZlciBDQTAeFw0xODA2MjcwMDAwMDBaFw0yMDA2MjAxMjAwMDBa
MGoxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1T
YW4gRnJhbmNpc2NvMRUwEwYDVQQKEwxHaXRIdWIsIEluYy4xFzAVBgNVBAMTDnd3
dy5naXRodWIuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxjbK
Rw+cVNjgA/BhLfRTOAk6jRGT7WRmmWy/qhFmTxBKapW/Kh4UNeD7oUAB0yG+Fyvu
1grVYR5RFUGBmA5mkqrBjCg4fNbFU9vLKIbkhpH3Jp2HVNLzvjzs/RqCN04MEc6M
nbmkjx1YeW9CveXojrt4x3Sa3nsPx6KcQtJpm8MuS8OhV2CJUF1etJpu9id5WJQd
U3j3h65PmXMBvunm7UaGDt2WVK4CRcIb6j0X3H4cjh4WhXLyMcSPutXZVoD0FSmY
+mjXVZCTJd+vHsYX1fj+kge20DJx0F8qmqJEr7bx1lfj7/U4aTgdZBDCB8wIl0fK
cOdR3wq2RrDVRUlOuQIDAQABo4IDyzCCA8cwHwYDVR0jBBgwFoAUUWj/kK8CB3U8
zNllZGKiErhZcjswHQYDVR0OBBYEFI+I3Dwd7kQJ5DCMBsoC859olPB5MHsGA1Ud
EQR0MHKCDnd3dy5naXRodWIuY29tggsqLmdpdGh1Yi5pb4IXKi5naXRodWJ1c2Vy
Y29udGVudC5jb22CDCouZ2l0aHViLmNvbYIKZ2l0aHViLmNvbYIJZ2l0aHViLmlv
ghVnaXRodWJ1c2VyY29udGVudC5jb20wDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQW
MBQGCCsGAQUFBwMBBggrBgEFBQcDAjB1BgNVHR8EbjBsMDSgMqAwhi5odHRwOi8v
Y3JsMy5kaWdpY2VydC5jb20vc2hhMi1oYS1zZXJ2ZXItZzYuY3JsMDSgMqAwhi5o
dHRwOi8vY3JsNC5kaWdpY2VydC5jb20vc2hhMi1oYS1zZXJ2ZXItZzYuY3JsMEwG
A1UdIARFMEMwNwYJYIZIAYb9bAEBMCowKAYIKwYBBQUHAgEWHGh0dHBzOi8vd3d3
LmRpZ2ljZXJ0LmNvbS9DUFMwCAYGZ4EMAQICMIGDBggrBgEFBQcBAQR3MHUwJAYI
KwYBBQUHMAGGGGh0dHA6Ly9vY3NwLmRpZ2ljZXJ0LmNvbTBNBggrBgEFBQcwAoZB
aHR0cDovL2NhY2VydHMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0U0hBMkhpZ2hBc3N1
cmFuY2VTZXJ2ZXJDQS5jcnQwDAYDVR0TAQH/BAIwADCCAX4GCisGAQQB1nkCBAIE
ggFuBIIBagFoAHYA7ku9t3XOYLrhQmkfq+GeZqMPfl+wctiDAMR7iXqo/csAAAFk
QsgYsgAABAMARzBFAiBe00KrPC3L9DUwJ0rYXoQ+Fh70UM3rYNyT9uLyEo1kfAIh
ALtR7krXouwsj4s52P2bWJiS0QKGLvbnBGnZLn4WNScDAHYAh3W/51l8+IxDmV+9
827/Vo1HVjb/SrVgwbTq/16ggw8AAAFkQsgYswAABAMARzBFAiB2wURHjtfhDN6l
3Q9gaYnu9h5xsFjJIOA3qO1dzqNVjQIhANPyeXq61y1gsHH/Iq2aqv43CMjjDQ8p
02baNg3puNoMAHYAu9nfvB+KcbWTlCOXqpJ7RzhXlQqrUugakJZkNo4e0YUAAAFk
QsgX9wAABAMARzBFAiEAhxuoQCyQzEoSK8/f4AXq+d0RZ3550opfcEty3p7gHyAC
IBZ3NXHCNZpH6ow7D/qUZcfXkuMk/aZvR9uHoVvkixbcMA0GCSqGSIb3DQEBCwUA
A4IBAQCjPNhowM6/PVcxHtl18r+92pPzU3JRGnXfz/P077yEgIIgs8I0lPqi9AiW
QYev56+Ar4a39y+666s55ogjIVL+7cboKPgqflEY1POCg64UZNDHHPTnd5ba2OUw
dtk1QtrEtYbUKm0W/1Ne9JRdN2rh5J87NsSPhirmKsP6HA3OhL93LTqB72Iehwj+
qmIrQhkhJiTReWTb5sNrD2gIt8Dhuts/M84a9v7Hrkq/VPYVmARm7Py0GC/jqxpI
NCHBEAFKN2c7iqmx1dVOGJDV3U0TCa0yWbnXsZ9M0652zH1obM3UxCtUMuUZzDb9
aTrrJ67dru040mysq2NLPPq+t+EQ
-----END CERTIFICATE-----
subject=C = US, ST = California, L = San Francisco, O = "GitHub, Inc.", CN = www.github.com

issuer=C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert SHA2 High Assurance Server CA

---
No client certificate CA names sent
Peer signing digest: SHA512
Peer signature type: RSA
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 3710 bytes and written 410 bytes
Verification: OK
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: E335D0E2DFA9C2306B94CA16B7DE49AC96A04490417DF355B0314DB4EC716090
    Session-ID-ctx:
    Master-Key: 68A4C1D03422D758D9A46B6DF3BE2C39250898ADADA65AC403B7D6CAAE2DD954E516383E45051FA8A9AA3F9B4E57B97F
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 7200 (seconds)
    TLS session ticket:
    0000 - 26 3f 8d 6c cf 78 df b6-93 4b 12 f3 63 d8 08 50   &?.l.x...K..c..P
    0010 - 54 d8 34 38 d2 76 7c c3-b8 71 11 52 f7 cb 9a 00   T.48.v|..q.R....
    0020 - 49 31 cd b1 fa 4d 53 2e-32 fb ff 6a bb 9d 7b 97   I1...MS.2..j..{.
    0030 - 8c cd 85 68 2d 85 c2 d5-a2 71 ac 7d 9f 9c 5f e6   ...h-....q.}.._.
    0040 - 41 7e f4 6a 14 d6 0c a3-76 bd 9a 25 39 a5 8f 72   A~.j....v..%9..r
    0050 - cc ab 60 62 ac 22 10 23-47 5b f1 d9 50 df 4b 6f   ..`b.".#G[..P.Ko
    0060 - 6b 98 07 7e 6d 07 a4 9e-83 91 9e 0a 9a 0b 71 de   k..~m.........q.
    0070 - df f0 7c c1 da fd 45 47-7a ea 8f f1 38 47 47 2f   ..|...EGz...8GG/
    0080 - 89 a6 f3 f2 39 d4 58 26-bf e3 94 86 7d e0 91 72   ....9.X&....}..r
    0090 - 6d 2a 39 fb d2 9f 6e 65-f3 3a 2e 81 72 59 99 10   m*9...ne.:..rY..
    00a0 - 52 8d 8e 7c f4 1a cd 36-15 0d 3b a3 fd cf 7f 67   R..|...6..;....g
    00b0 - c3 cb 0c 37 10 d4 65 3a-7a b7 54 b4 85 28 43 cd   ...7..e:z.T..(C.

    Start Time: 1585635795
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: yes
---

**Comment by fisadev** [comment]
Buenas!

Esto era un bug de github pages (que generan los certs), habían roto el tema de SSL con custom domains. Pero les hablé y hace poco lo solucionaron. Cierro el issue :)
