### ISSUE TITLE
Error installing fisa-vim-config on Windows 10

### ISSUE THREAD

**Issue by sbacelar** [fisadev/fisa-vim-config#123]
I had no problem installing this config on `Linux` and on `Mac`. But when I try to install it on `Windows` the installation process does not finish. Is there any change in this config to for it to work on `Windows`?

**Comment by fisadev** [comment]
Sorry, I do not test it under Windows, and there are probably several issues with it. The most obvious one must be the lack of curl (which is used to download vim-plug for the first time).

I can't add the support for it by myself (lack of time for all the extra work that would mean, mostly), but I don't have any issues with people adding support if that isn't too hacky. I'm closing this issue for now, but if you wanted to work on it and open MRs related to Windows, I can test that they don't break the Linux functionality.
