### ISSUE TITLE
Virtualenv integration

### ISSUE THREAD

**Issue by kpace** [fisadev/fisa-vim-config#124]
Hello there and thanks a lot for this config file. I find it very useful! 🙏 

I am working on multiple Python projects using different virtualenvs for each. I would like to be able to use different python interpreters for autocompletion, documentation, etc.

Is it possible to use this configuration with different virtual environments and changing the current virtualenv on the fly? 

Thanks!

**Comment by kpace** [comment]
[SOLVED]

After reading [this](https://github.com/deoplete-plugins/deoplete-jedi#virtual-environments), I was able to activate virtualenv in NeoVim.

**Comment by fisadev** [comment]
Thank you and sorry for the delay! Awesome that you found a solution :)
