### ISSUE TITLE
[vim-hug-neovim-rpc] requires one of `:pythonx import [pynvim|neovim]`

### ISSUE THREAD

**Issue by ajinzrathod** [fisadev/fisa-vim-config#129]
When I use  a virtual environment for python projects, I am getting this error.

`[vim-hug-neovim-rpc] requires one of :pythonx import [pynvim|neovim]`

I saw lot of issues in github but none of them solved mine

And when I install `neovim` and `pynvim` in virtualenv, it shows Requirement Already Satisfied.

**Comment by fisadev** [comment]
Hi! Is this happening with vim or neovim? Are you on the latest version of the config? Any modifications made to the config?
And are the virtualenvs python2 or python3?

**Comment by ajinzrathod** [comment]
Yes, I am using the latest version.

I have 3 python versions in my PC
1. python2.7
2. python3.6
3. python3.7

I have installed Virtual Envs in 3.7
Yes, I have made certain changes.
See [here](https://github.com/ajinzrathod/vim/blob/master/vimrc)

But I have only added `Syntastic Check` and `NERDTree` 

Its working totally fine WITHOUT `virtualenv`
It causes error only in `virtualenv`

And I am using `vim`

Please solve my issue, without this autocomplete is not working and do not want to shift to emacs or sublime.
Please help me

![Screenshot from 2020-06-23 21-23-02](https://user-images.githubusercontent.com/57681532/85426292-e7b04700-b597-11ea-9797-467dbd6d2c7e.png)

**Comment by fisadev** [comment]
The most probable cause is that you installed all the dependencies outside the virtualenv, but you are now using the editor from inside the virtualenv.
You have two options: you can launch the editor from outside the virtualenv, or you can install the config dependencies inside the virtualenv too.

**Comment by ajinzrathod** [comment]
```
(opencv) ajinzrathod@ajinz:~/Documents/project-of-opencv-venv$ pip list

DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
greenlet (0.4.16)
msgpack (1.0.0)
neovim (0.3.1)
numpy (1.19.0)
opencv-python (4.2.0.34)
Pillow (7.1.2)
pip (9.0.1)
pkg-resources (0.0.0)
pynvim (0.4.1)
scikit-video (1.1.11)
scipy (1.5.0)
setuptools (39.0.1)

```

I do not want to launch outside venv.

You can see I have already installed `pynvim` and `neovim`. Correct me if I m wrong?
:-(

**Comment by fisadev** [comment]
Ok, I'm able to reproduce the issue here, it seems like a bug/problem in Deoplete while in Vim. I'll try to see if I can find a fix, but I can't promise anything. In the meantime, an option is to switch to NeoVim, which doesn't have this problem.

**Comment by ajinzrathod** [comment]
Ok. Thanks

**Comment by pilot513** [comment]
Hi.
What is the news on this issue?
I have a similar problem on ubuntu 20.04 LTS with python2.7/3

pip list

`
Package                       Version
----------------------------- -----------
backports.functools-lru-cache 1.6.1
configparser                  4.0.2
contextlib2                   0.6.0.post1
enum34                        1.1.10
flake8                        3.8.3
functools32                   3.2.3.post2
futures                       3.3.0
importlib-metadata            1.6.1
isort                         4.3.21
mccabe                        0.6.1
pathlib2                      2.3.5
pep8                          1.7.1
pip                           20.1.1
pycodestyle                   2.6.0
pyflakes                      2.2.0
scandir                       1.10.0
setuptools                    44.1.1
six                           1.15.0
typing                        3.7.4.1
wheel                         0.34.2
yapf                          0.30.0
zipp                          1.2.0`

**Comment by ajinzrathod** [comment]
@pilot513 
you should try
`pip install neovim` inside Virtual Environment

**Comment by pilot513** [comment]
I install neovim. Now probles solved in vim/nvim.
Thanks.

**Comment by fisadev** [comment]
ok, that's super weird. In theory that package was deprecated and replaced with pynvim, and installing pynvim in the venv the editor should be able to do "import neovim", because pynvim keeps that for compatibility.

**Comment by ajinzrathod** [comment]
I created another virtual environment and tried:

```
pip install neovim
pip install pynvim
pip install vim
pip install jedi
```

And its working fine in my new virtual environment.

I think there is some issue with virtual environment.
Thank you :+1:
