### ISSUE TITLE
How do I change the theme?

### ISSUE THREAD

**Issue by Ron-SK** [fisadev/fisa-vim-config#131]

**Comment by fisadev** [comment]
Hey! Sorry for the delay. Just in case anyone else reaches this issue:

You can just modify this block:

```vim
" use 256 colors when possible
if has('gui_running') || using_neovim || (&term =~? 'mlterm\|xterm\|xterm-256\|screen-256')
    if !has('gui_running')
        let &t_Co = 256
    endif
    colorscheme vim-monokai-tasty
else
    colorscheme delek
endif
```
This `if` basically chooses `vim-monokay-tasty` when running in GUI or a terminal with enough colors, or `delek` in more primitive environments. You can just remove the whole block, and leave something like:

```vim
colorscheme my-favorite-super-fancy-theme
```
