### ISSUE TITLE
MatchTagAlways unavailable

### ISSUE THREAD

**Issue by mac4br3** [fisadev/fisa-vim-config#137]
Error detected while processing /home/sherlock/.vimrc:
line  358:
E117: Unknown function: deoplete#custom#option
MatchTagAlways unavailable: requires python.
Press ENTER or type command to continue

**Comment by codinghedgehog-python** [comment]
I'll second that.

After I installed the Python plugin into Vim on Kali Linux and opened a py file I get this:

```
E605: Exception not caught: No python support present, vim-isort will be disabled
MatchTagAlways unavailable: requires python.
```

Python is installed and vim-isort is installed by running `pip3 install isort`

OS: Kali Linux

**Comment by ihuertat** [comment]
> I'll second that.
> 
> After I installed the Python plugin into Vim on Kali Linux and opened a py file I get this:
> 
> ```
> E605: Exception not caught: No python support present, vim-isort will be disabled
> MatchTagAlways unavailable: requires python.
> ```
> 
> Python is installed and vim-isort is installed by running `pip3 install isort`
> 
> OS: Kali Linux

Go to de line and change python to python3 instead.. it probably is the bug.

**Comment by mac4br3** [comment]
*thank you guys for your support*
