### ISSUE TITLE
Add cronex plugin

### ISSUE THREAD

**Issue by cacrespo** [fisadev/fisa-vim-config#149]
Hi Fisa!
Check out this wonderful plugin: [cronex.nivm](https://github.com/fabridamicelli/cronex.nvim)
Human-readable inline cron expressions in Neovim.
![image](https://github.com/fisadev/fisa-vim-config/assets/10950697/deba8199-2725-41aa-8a50-a7c50fb619ab)

I'm not sure if it works on vim, but it's great on nvim and provides a nice improvement. 
:rocket: :rocket: :rocket:

**Comment by baco** [comment]
@cacrespo it certainly won't work on Vim.  It's written in Lua and the _virtual-text_ feature is using to display the “Human-readable expression” doesn't come in Vim

**Comment by fisadev** [comment]
Hi! Sadly what Baco said is true, it doesn't work with neovim :(

**Comment by cacrespo** [comment]
I understand... thank you both for the replies. Closing the issue. 😢
