### ISSUE TITLE
vim_debug not found & error in vim-isort in Ubuntu 13.10

### ISSUE THREAD

**Issue by ankitksharma** [fisadev/fisa-vim-config#65]
I am getting two error when I am trying to open a file in VIM using fisa-vim-config 
1. Python module vim_debug not found
2. Error detected while processing ~/.vim/bundle/vim-isort/ftplugin/python_vimisort.vim (this is coming when I am opening python files)

I have Anaconda python and it is set in path. I have installed vim-debug using pip command and it is installed in my python directory and .vim directory as well.

Can you please suggest what could be the issue and how to rectify it?

**Comment by johnrlive** [comment]
I deleted the following file "~/.vim/bundle/vim-debug.vim/plugin/debugger.vim" and I no longer get the "Python module vim_debug not found..." message. Thanks @ankitksharma

**Comment by fisadev** [comment]
Update on this: the newest version of the config no longer has that problematic debugger. And it also changed the plugin manager for another better one :) More info at http://fisadev.github.io/fisa-vim-config/ (be sure to click on the "upgrade" link to see the upgrade instructions)
