### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'major'

### ISSUE THREAD

**Issue by daiqingyang** [fisadev/fisa-vim-config#76]
![a](https://cloud.githubusercontent.com/assets/5936574/5834355/a314d5a8-a197-11e4-95e6-7a10e85d1b52.png)
when start vim ,throw this error,is it something wrong with my config?
=========================================================

**Comment by fisadev** [comment]
strange! let me update my plugins and test, and I'll post any findings/fixes

**Comment by fisadev** [comment]
I can't reproduce it. Can you paste the output of this?:

    vim --version

Please use some kind of pastebin to paste the text, don't do a screenshot, so I'm able to search for some bits in the very long output :) (you can use http://linkode.org/ and give me the url)

**Comment by daiqingyang** [comment]
hello it is here 
http://linkode.org/ZbrpeOn4niQHG67JhchPk6

**Comment by daiqingyang** [comment]
here is vim version 
http://linkode.org/ZbrpeOn4niQHG67JhchPk6

**Comment by fisadev** [comment]
Which OS are you using? How did you install vim? Can you run this inside vim and tell me the output?:

    :python import sys;print sys.version;print sys.version_info;print type(sys.version_info)

**Comment by daiqingyang** [comment]
NORMAL >> [No Name]                                                                 << [unix] < 100% :   0:  0  
:!python -c "import sys;print sys.version;print sys.version_info;print type(sys.version_info)"
2.6.6 (r266:84292, Jan 22 2014, 09:42:36) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)]
(2, 6, 6, 'final', 0)
<type 'tuple'>

Press ENTER or type command to continue

**Comment by fisadev** [comment]
No no, don't run it with !. Run it as I wrote it. If you use !, you are
running your system's python interpreter. Without ! you run it on vim's own
python interpreter, which is the one that the plugins use, the one raising
the error.

**Comment by fisadev** [comment]
Also, don't add -c and the " ". Run it exactly as I wrote it :)

**Comment by daiqingyang** [comment]
I'm sorry,the output is below.
======================
NORMAL >> 1.py                                                < python < utf-8[unix] <   4% :   1:  1   [Syntax: line:6 (30)]  
2.6.6 (r266:84292, Jan 22 2014, 09:42:36)  sys.version_info;print type(sys.version_info)
                                          [GCC 4.4.7 20120313 (Red Hat 4.4.7-4)]
                                                                                (2, 6, 6, 'final', 0)
                                                                                          9      2   2type 'tuple'>

**Comment by fisadev** [comment]
Ok! I know what is the problem then. For some reason, the python interpreter in your vim returns a tuple instead of a version_info object in the function sys.version_info(). This function is used in one of the plugins, which checks for an attribute of the returned object. This attribute doesn't exist in tuples, just in system_info objects.
Luckily, the plugin is mine, so I can fix it. I'll do it later and let you know when you can update and test it :)

**Comment by fisadev** [comment]
Done! You just need to update your plugins, to do that run in vim (exactly as I write it, with the ! and everythong):

    :BundleInstall!

**Comment by daiqingyang** [comment]
it works!! Thank you so much.
