### ISSUE TITLE
how to modify  pep8's character size rather than the default 79 characters

### ISSUE THREAD

**Issue by daiqingyang** [fisadev/fisa-vim-config#77]
when coding ,show the tip "E501 line too long (87 > 79 characters)",how to hack it..? it is to short for me..
===============================================================================

**Comment by fisadev** [comment]
Look for the syntastic settings in your .vimrc, and add this below them:

    let g:syntastic_python_flake8_args="--max-line-length=160" 

(where 160 is the line length you wish to use)

**Comment by fisadev** [comment]
Closing this issue as solved, if it's not solved just reopen it :)

**Comment by nqiu** [comment]
I put the line `let g:syntastic_python_flake8_args="--max-line-length=160"` below the other syntastic settings, but it didn't work even if I reopened the .py file.

The related configuration is as below,

```

" Syntastic ------------------------------

" show list of errors and warnings on the current file
nmap <leader>e :Errors<CR>
" check also when just opened the file
let g:syntastic_check_on_open = 1
" don't put icons on the sign column (it hides the vcs status icons of signify)
let g:syntastic_enable_signs = 0
" custom icons (enable them if you use a patched font, and enable the previous
" setting)
"let g:syntastic_error_symbol = '✗'
"let g:syntastic_warning_symbol = '⚠'
"let g:syntastic_style_error_symbol = '✗'
"let g:syntastic_style_warning_symbol = '⚠'
let g:syntastic_python_flake8_args="--max-line-length=120"

" Jedi-vim ------------------------------
```

**Comment by fisadev** [comment]
Did you reload your vim config after adding that line? You can easily do that by closing and re opening vim
