### ISSUE TITLE
The airline statusline funcref ...has already been added.

### ISSUE THREAD

**Issue by leshow** [fisadev/fisa-vim-config#80]
Not quite sure what went wrong here but I don't have airline enabled and i'm getting this error:

on arch with everything up to date, followed the readme for the install process

```
".vimrc" 419L, 12904C
The airline statusline funcref function('airline#extensions#ctrlp#apply') has already been added.
The airline statusline funcref function('airline#extensions#netrw#apply') has already been added.
The airline statusline funcref function('airline#extensions#quickfix#apply') has already been added.
```

**Comment by leshow** [comment]
sorry, removing vim-airline installed from AUR removed this error

**Comment by fisadev** [comment]
Ok! Thanks for reporting and for posting the solution :)

**Comment by felipealfonsog** [comment]
> sorry, removing vim-airline installed from AUR removed this error

fantastic! You got it! ... Thanks for posting the fix!
