### ISSUE TITLE
I want to know how to use the font which in the screenshot, it is beautiful 

### ISSUE THREAD

**Issue by axiaoxin** [fisadev/fisa-vim-config#81]
Thank you

**Comment by fisadev** [comment]
You can download the font from this website: http://cooltext.com/Download-Font-CPMono
Then, install it (on ubuntu just double click the font file, then click on "install") and configure your terminal to use it.

Also, if you want to use the special (nicer) symbols for the status line, follow this:
https://github.com/fisadev/fisa-vim-config#optional-fancy-symbols-and-breadcrumbs-in-the-status-line

:)

**Comment by axiaoxin** [comment]
thank you very much
