### ISSUE TITLE
Installation Color scheme.

### ISSUE THREAD

**Issue by 0x2F** [fisadev/fisa-vim-config#83]
[n1c @ yard]->vim .vimrc 
Error detected while processing /home/n1c/.vimrc:
line  193:
E185: Cannot find color scheme 'fisa'
Press ENTER or type command to continue

**Comment by fisadev** [comment]
Can you try re-running the ``:BundleInstall!`` command? (with the "!" included). Its a common problem to have a "partial" installation due to network problems while cloning the plugins for the first time, which can generate problems like that.

**Comment by 0x2F** [comment]
I installed the colors manually, just wanted to report a bug, for future users :)
