### ISSUE TITLE
Error when install airline plugin in vim?

### ISSUE THREAD

**Issue by vanloc0301** [fisadev/fisa-vim-config#86]
I don't experience to use vim. I try to install plugin for vim from this site:

[fisa-vim-config for python][1]

After installing plugin success. It shows error like:

[Image show error information][2]

I know this question is stupid. But I searched many internets but this error not found.

  [1]: https://github.com/fisadev/fisa-vim-config/blob/master/.vimrc
  [2]: http://i.stack.imgur.com/RBIqD.png

**Comment by fisadev** [comment]
Hey, did it happen only the first time? If so, this is normal, airline fails to load the first time during installation. Just close vim and reopen it, and it should be working.

If it keeps happening after the installation, let me know and I'll try to fix it.

**Comment by fisadev** [comment]
Closing as it was a known issue with Vundle, and now the config migrated to VimPlug, which works like a charm :)
