### ISSUE TITLE
'scrooloose/syntastic' slows down search

### ISSUE THREAD

**Issue by lixiaonin** [fisadev/fisa-vim-config#87]
Used this setup for a django project for a while, found that this syntastic plugin slows down the global search a lot, for example ':vim /<pattern>/ **/*.py'. 
Did I missed anything or if i'm right, are there any better alternatives?

**Comment by fisadev** [comment]
Let me try, I didn't notice that before. If it's slowing it down I may look for alternatives.

**Comment by lixiaonin** [comment]
thx! 
I knew that adding any plugin can slow down vim a little little bit, cause I tried pure native vim. But in my tests, only this one slows down two or three times more.(with all other conditions and path the same when testing.)
Found keyword 'request.session' in whole project in 4-5 seconds without syntastic, and 20+seconds with it.

**Comment by fisadev** [comment]
ufff, that's a very big slow down!

**Comment by fisadev** [comment]
I think I found a workaround which doesn't disable syntastic, but makes it faster in many cases. Can you try it? Just add this to your .vimrc:

`let g:syntastic_check_on_open = 1`

Then restart vim, and test the performance on that same search. If that fixes it, I'll probably add it as default on the config.

**Comment by lixiaonin** [comment]
thx for your effort, but that line seems there already in the very beginning even before I tried out, in your code, around 312 line. 
and i just tried with another python project on another machine(vim 7.4), the result is : around 5 seconds without syntastic, and 50+ seconds with it.

**Comment by fisadev** [comment]
sorry! made a typo. I wanted you to try the opposite to that, hehe. My bad:

`let g:syntastic_check_on_open = 0`

:)

**Comment by lixiaonin** [comment]
it works like a miracle !
Thx, I appreciate it.

**Comment by fisadev** [comment]
The only downside to that setting is that syntastic won't check for errors when you open a file, you will need to save it once for the checks to be ran.

**Comment by lixiaonin** [comment]
yeah, i'd be more careful, not rely too much on the checker haha. thanks man.

**Comment by fisadev** [comment]
you are welcome, glad it helped!
