### ISSUE TITLE
NameError: name 'rope' is not defined

### ISSUE THREAD

**Issue by jordanjambazov** [fisadev/fisa-vim-config#94]
Hi,

When I try to go to definition (`,D`), I get the following error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'rope' is not defined
```

I already performed did check similar issues like:
https://github.com/fisadev/fisa-vim-config/issues/63
https://github.com/klen/python-mode/issues/437

Vim is compiled with +python:

```
# vim --version | grep python
+cryptv          +linebreak       +python          +vreplace
+cscope          +lispindent      -python3         +wildignore
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.22/CORE -lperl -ldl -lm -lpthread -lcrypt -L/usr/lib/python2.7/config-x86_64-linux-gnu -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions  -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lieee -lm -lruby-2.3 -lpthread -lgmp -ldl -lcrypt -lm
```

Rope is enabled in .vimrc: `let g:pymode_rope = 1`

Could you please help with some additional insights?

Environment:
Fisa VIM Config version: 8.1
OS: Ubuntu 16.04 LTS

Edit: happens after a clean install. The `.vim` folder and `.vimrc` were not present.

**Comment by fisadev** [comment]
Can you try this and tell me what it prints at steps 2 and 3?:

1. Open a .py file with vim
2. With the .py file opened, run this command: ``:py import rope``
3. After that, run this other command: ``:py print dir(rope)``

Also, how did you install vim? By default in Ubuntu 16.04 it doesn't have +python, so you must have installed some other package to add the python support. Which one? (so I can test with your exact same version here).

**Comment by jordanjambazov** [comment]
`:py import rope` - success
`:py print dir(rope) - ['COPYRIGHT', 'INFO', 'VERSION', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__']
`:py print rope` - <module 'rope' from '/home/jordan/.vim/plugged/python-mode/pymode/libs2/rope/__init__.pyc'>

That is using the `vim-nox-py2` package in Ubuntu. Seems that the original issue which I reported disappeared now, but when I attempt to go to definition (`,D`):

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'goto'
```

**Comment by knightseu** [comment]
Any updates? I have exactly the same issue. I am using mac.

**Comment by cundi** [comment]
Same problem here.

**Comment by fisadev** [comment]
Hey, I decided to finally ditch rope in favor of a combination of other plugins which work a lot better (for python autocompletion, go to definition, etc).

Is anyone willing to try the new set of plugins? It's just a matter of getting a new config from a different branch, and running a pair of commands.

**Comment by ezetl** [comment]
Im having the exact same problem on a mac, I'm willing to try the new set of plugins, just tell me how and which branch :)

**Comment by fisadev** [comment]
This is the temporary branch with that change: nvim-backport-remove-python-mode

You should replace your ``.vimrc`` with the one from that branch, and then run (from inside vim) these commands (in order):

    :PlugClean
    :PlugInstall
    :PlugUpdate

After that, you can test it with any python project. Try to use the autocompletion, and the "go to definition" feature (mapped to ``,d``). They should work as intended, and you shouldn't get any import errors from rope, because it won't be used anymore.

**Comment by ezetl** [comment]
It worked like a charm, thanks fisa (:

**Comment by knightseu** [comment]
I get following error: "Please Install Jedi if you want to use jedi-vim". And I did install Jedi

**Comment by knightseu** [comment]
Here is the error when I try to use ',d' -
~/dev-src/deploy_stack/deploy-tools/src/deploy_tools/controllers/maven_artifact_controller.py" 389L, 14432C
Please install Jedi if you want to use jedi-vim.
The error was: dlopen(/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder^@  Referenced from: /usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/V
ersions/2.7/lib/python2.7/lib-dynload/_io.so^@  Expected in: flat namespace^@ in /usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so

**Comment by fisadev** [comment]
Are you running Mac OS? That seems to be a problem outside vim. Some people having that problem under Mac OS have fixed it running this command: 

    $ hash -r python

Can you try that?

**Comment by knightseu** [comment]
That does not help, but you are right, that does look like something outside vim.

**Comment by fisadev** [comment]
Something you could try is to run that from inside vim's process, like this:

    :!hash -r python

I'm guessing it could help based on what others tell about the problem, but I have no mac to test it myself.
