### ISSUE TITLE
Fugitive for Git integration.

### ISSUE THREAD

**Issue by chillipeper** [fisadev/fisa-vim-config#97]
Hey,

I am very new on the vim world, and have found your vim config very handy.
I have one particular question, I have noticed that for Git Integration you are using motemen/git-vim instead of tpope/vim-fugitive. 

I am not sure if motemen/git-vim is mantained anymore, I see that the latest update was on 2012.

Is there any particular reason you are using this plugin instead of fugitive?

**Comment by fisadev** [comment]
You are right, git-vim seems pretty abandoned. I'll look into fugitive, and if nothing breaks I'll make the switch in the next release :)

**Comment by fisadev** [comment]
Small update on this: I'm using fugitive right now, but under neovim and it works fine. I'm planning on releasing a neovim config, but I'll also update this config migrating to fugitive. Thanks for the suggestion! :)

**Comment by chillipeper** [comment]
Sorry for the late response, and thanks so much :)

**Comment by fisadev** [comment]
The latest release, which merges the neovim and vim configs in this single config to rule them all, uses fugitive as the git plugin :)
